#! /bin/sh
$HOME/.config/bspwm/autostart

FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
ACCENT=$(xrdb -query | grep 'accent:'| awk '{print $NF}')

bspc monitor DP-2 -d 1 2 3 4 5
bspc monitor DP-0 -d 6 7 8 9 10
bspc monitor DP-0 -s DP-2

bspc config border_width            1
bspc config window_gap              15
bspc config normal_border_color     "$BACKGROUND"
bspc config focused_border_color    "$ACCENT"
bspc config presel_feedback_color   "$BACKGROUND"

bspc config split_ratio             0.5
bspc config borderless_monocle      false
bspc config gapless_monocle         false

bspc config focus_follows_pointer   true
